#!/bin/bash
./cleanmodules
make modules_install
echo copying kernel and modules
tar -C /tmp/dist --exclude='lib/modules/*/build' --exclude='lib/modules/*/source' -czf modules.tgz lib
scp modules.tgz arch/arm/boot/zImage root@de10nano:
