#!/bin/bash
echo copying kernel
scp arch/arm/boot/zImage overlay.dtso root@de10nano:
cd /tmp/dist
rm -rf /tmp/dist/lib/modules/*/build
rm -rf /tmp/dist/lib/modules/*/source
tar czf /tmp/modules.tgz *
cd
scp /tmp/modules.tgz root@de10nano:
