#ifndef __MINER_H
#define __MINER_H

#define MINER_DRIVER_MAJ 1
#define MINER_DRIVER_MIN 2

#define EOK 0

#define REG_BYTES 4

#define MINER_SOLN_REG 0
#define MINER_STATUS_REG 2
#define MINER_SHA3_REG 3
#define MINER_HDR_REG 4
#define MINER_DIFF_REG 12
#define MINER_START_REG 20
#define MINER_CTL_REG 22
#define MINER_REGS (MINER_CTL_REG + 1)

#define MINER_SOLN_REG_B (MINER_SOLN_REG * REG_BYTES)
#define MINER_STATUS_REG_B (MINER_STATUS_REG * REG_BYTES)
#define MINER_SHA3_REG_B (MINER_SHA3_REG * REG_BYTES)
#define MINER_HDR_REG_B (MINER_HDR_REG * REG_BYTES)
#define MINER_DIFF_REG_B (MINER_DIFF_REG * REG_BYTES)
#define MINER_START_REG_B (MINER_START_REG * REG_BYTES)
#define MINER_CTL_REG_B (MINER_CTL_REG * REG_BYTES)

#define MINER_CTL_RUN_MASK 0x00000001u
#define MINER_CTL_RUN_SHIFT 0u
#define MINER_CTL_TEST_MASK 0x00000002u
#define MINER_CTL_TEST_SHIFT 1u
#define MINER_CTL_LAST_MASK 0x00FF0000u
#define MINER_CTL_LAST_SHIFT 16u
#define MINER_CTL_FIRST_MASK 0xFF000000u
#define MINER_CTL_FIRST_SHIFT 24u

#define MINER_STATUS_FOUND_MASK 0x00000001u
#define MINER_STATUS_FOUND_SHIFT 0u
#define MINER_STATUS_RUN_MASK 0x00000002u
#define MINER_STATUS_RUN_SHIFT 1u
#define MINER_STATUS_TEST_MASK 0x00000004u
#define MINER_STATUS_TEST_SHIFT 2u
#define MINER_STATUS_MHZ_MASK 0x0000ff00u
#define MINER_STATUS_MHZ_SHIFT 8u
#define MINER_STATUS_MAJ_MASK 0x000f0000u
#define MINER_STATUS_MAJ_SHIFT 16u
#define MINER_STATUS_MIN_MASK 0x00f00000u
#define MINER_STATUS_MIN_SHIFT 20u

#define MINER_DRIVER_VERSION_MIN_MASK 0x0000000fu
#define MINER_DRIVER_VERSION_MIN_SHIFT 0u
#define MINER_DRIVER_VERSION_MAJ_MASK 0x000000f0u
#define MINER_DRIVER_VERSION_MAJ_SHIFT 4u

#endif /* __MINER_H */
